---
title: "Homework 5: Linear Mixed Models"
author: "your name"
date: 'Due: April 7th at 11:59 PM'
output: pdf_document
header-includes: 
 - \usepackage{amsthm}
 - \usepackage{amsmath}
 - \usepackage{amsfonts}
 - \usepackage{amscd}
 - \usepackage{amssymb}
 - \usepackage{natbib}
 - \usepackage{url}
---

\allowdisplaybreaks

\newcommand{\Var}{\mathrm{Var}}
\newcommand{\Prob}{\mathbb{P}}
\newcommand{\E}{\mathrm{E}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\inner}[1]{\langle #1 \rangle}
\newcommand{\yobs}{y_{\text{obs}}}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



**Problem 1**: Prove that intraclass correlation between observations at the same level is formally expressed as 
$$
  \rho = \frac{\sigma_\alpha^2}{\sigma_\alpha^2 + \sigma_\varepsilon^2},
$$
and discuss the implications of a value of $\rho$ close to zero or one.

\vspace*{0.5cm}

**Problem 2**: Do the following with the pulp data set:  

\begin{enumerate}
	\item[(a)] Analyze the pulp data in the notes using unrestricted maximum likelihood estimation and comment on the differences that such analysis produces when compared to the REML and ANOVA estimates.
	\item[(b)] Interpret the diagnostic plots in the notes corresponding to the analysis with respect to the pulp data set; conclude that these plots indicate no particular problems.
\end{enumerate}


\vspace*{0.5cm}


**Problem 3**: Do the following: 
\begin{enumerate}
	\item[(a)] Compare and contrast the nonparametric bootstrap, residual bootstrap, and parametric bootstraps. Discuss the assumptions that make each bootstrap procedure appropriate. There is a useful guide embedded in the course notes.
	\item[(b)] In the notes we developed a parametric bootstrap procedure to approximate the distribution of the LRT corresponding to a test between mixed-effects models. Write your own parametric bootstrap procedure with $B= 1e4$ samples and make it as fast as possible using parallel programming with either \texttt{mclapply} and/or \texttt{foreach} and whatever accompanying software packages are needed.
	\item[(c)] Explain how the testing procedure using the \texttt{exactRLRT} function works. See the analysis of the irrigation data in the LMM course notes for context.
\end{enumerate}


\vspace*{0.5cm} 


**Problem 4**: The \texttt{denim} dataset in the \texttt{faraway} concerns the amount of waste in material cutting for a jeans manufacturer due to five suppliers. 
\begin{itemize}
  \item[(a)] Plot the data and comment.
  \item[(b)] Fit the linear fixed effects model. Is the supplier significant?
  \item[(c)] Make a useful diagnostic plot for this model and comment.
  \item[(d)] Analyze the data with supplier as a random effect. What are the estimated standard deviations of the effects?
  \item[(e)] Test the significance of the supplier term.
  \item[(f)] Compute confidence intervals for the random effect SDs.
  \item[(g)] Locate two outliers and remove them from the data. Repeat the fitting, testing and computation of the confidence intervals, commenting on the differences you see from the complete data. 
  \item[(h)] Estimate the effect of each supplier. If only one supplier will be used, choose the best.	
\end{itemize}


\vspace*{0.5cm}


**Problem 5**: Load in the \texttt{soybean\_full} dataset and analyze the \texttt{tqM} response variable. Refer to the analysis of the \texttt{AqE} response in the course notes, and recall that the researchers are interested in determining which ID variables differ from the RC reference level. Consider response transformations if modeling assumptions are violated. Do attempts to rectify departures from modeling assumptions affect the conclusions?


\vspace*{0.5cm}


**Problem 6**: Prove that the penalized weighted residual sum-of-squares problem can be cast as
$$
  r^2(\theta,\beta,u) 
    = r^2(\theta) + \|L_\theta^T(u - \mu_{U|Y=\yobs})  + R_{ZX}(\beta - \hat\beta_\theta)\|^2
      + \|R_X(\beta - \hat\beta_\theta)\|^2.
$$
See the LMM notes for context.
